using System.Collections.ObjectModel;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace H.Test.DataGrid
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();

            this.Students = new ObservableCollection<Student>
            {
                new Student { Name = "Alice", Age = "20", Email = "908293466@qq.com" }
            };
        }

        public ObservableCollection<Student> Students
        {
            get { return (ObservableCollection<Student>)GetValue(StudentsProperty); }
            set { SetValue(StudentsProperty, value); }
        }

        // Using a DependencyProperty as the backing store for MyProperty.  This enables animation, styling, binding, etc...
        public static readonly DependencyProperty StudentsProperty =
            DependencyProperty.Register("Students", typeof(ObservableCollection<Student>), typeof(MainWindow), new FrameworkPropertyMetadata(default(ObservableCollection<Student>), (d, e) =>
            {
                MainWindow control = d as MainWindow;

                if (control == null) return;

                if (e.OldValue is ObservableCollection<Student> o)
                {

                }

                if (e.NewValue is ObservableCollection<Student> n)
                {

                }

            }));




    }

    public class Student
    {
        public string Name { get; set; }
        public string Age { get; set; }
        public string Email { get; set; }
    }

    public class MyDataGrid : System.Windows.Controls.DataGrid
    {
        protected override void OnAutoGeneratedColumns(EventArgs e)
        {
            base.OnAutoGeneratedColumns(e);
        }

        protected override void OnAutoGeneratingColumn(DataGridAutoGeneratingColumnEventArgs e)
        {
            base.OnAutoGeneratingColumn(e);

            if (e.Column.Header == "操作")
                e.Column.
        }
    }
}